### PR TITLE
Add meme

### PR DESCRIPTION
**Pull request by jayrobwilliams**
A function to add memes to `memer`'s internal list of memes as discussed in #9.

### CODE REVIEW

**Comment by sctyner** [comment]
You forgot to export your function! No worries - I will accept the PR and revise.

**Comment by jayrobwilliams** [comment]
I left it internal so that regular users wouldn't stumble across it and be unable to get it to work since you have to recompile for the new meme to work. Might be a good idea to add a warning about this behavior to the details field before exporting it. Thanks for accepting!

**Comment by sctyner** [comment]
Good point! I'm not sure what the best way to handle this is. 🤷‍♀️

**Comment by jayrobwilliams** [comment]
Could just leave it unexported and add a note to the details as anyone who finds it via `:::` should be able to understand its limitations? No idea either.

**Pull request merged**
