### PR TITLE
Adding a Function to Post R Memes directly to Twitter

### PR DESCRIPTION
**Pull request by favstats**
Hi there :)

I created the function `tweet_meme` to post R memes directly to Twitter (mostly a wrapper around [rtweet's post_tweet](https://github.com/mkearney/rtweet/blob/master/R/post.R#L64)).

There is also the possibility to add "#rstats #rstatsmemes @rstatsmemes" to your post so the community can enjoy the meme :)

I am not super experienced with developing packages and my code to include the Twitter token might be a bit wonky. So please let me know if I can improve on this in any way :)

Oh and thank you for this great package! It's a really cool idea!!

### CODE REVIEW

**Comment by sctyner** [comment]
The travis build fails because the magick package is currently failing on travis so I'm ok with that. The appveyor build is failing because you need to add rtweet to suggests in the description file. It looks good otherwise. Two things before I accept the pull request: 

1. Add `rtweet` to suggests in the [description](http://r-pkgs.had.co.nz/description.html) file. 
2. Rename your tweeting function to match the rest of the functions in the package: i.e. meme_*

Thanks! 
```{r}
meme_get("ExpandingBrain") %>% 
  meme_text_brain("Sharing memes online", "Making your own memes", 
                   "Making memes in R", "Using rtweet to share your memes", size = 17)
```
image

**Comment by favstats** [comment]
Love that meme! 😆 

Thank you so much for the quick feedback! I will make the suggested changes ASAP.

**Comment by favstats** [comment]
I added rtweet to `Suggests:` but appveyor still fails to build. 

Any suggestions? Does it need to be imported instead?

**Comment by sctyner** [comment]
Ok. I think I see the issue. using `ImportFrom` requires the package you're importing from be in the Imports section. (This seems rather obvious in hindsight. Whoops.) Instead of importing, use `rtweet::post_tweet` in the function instead. You can uncomment the line containing `rtweet:::check_token` as I'm pretty sure that's not causing any issues. Importing `rtweet` seems excessive to me since only one function requires it, whereas most others explicitly require the `magick` package. This should fix the appveyor checks

**Comment by favstats** [comment]
Yes, completely agree that importing the whole `rtweet` package seems excessive. I've never used `ImportFrom`, thank you for clarifying! Seems like we got through that one error. 

Now the example seems to throw an error because it requires a token. I guess I can just write a custom message when no token is found? Or is there a way to do something like eval=F for the example (if that makes sense)?

**Comment by sctyner** [comment]
Use [dontrun](https://stackoverflow.com/questions/12038160/how-to-not-run-an-example-using-roxygen2) on the `meme_tweet` example.

**Comment by favstats** [comment]
Yay, that worked! 🎆 I am learning a lot through this, thanks a lot! :)

**Comment by sctyner** [comment]
Thanks! I'll accept the pull request now! I'm probably going to change how the tokens are dealt with, but this is great work! 😄

**Comment by favstats** [comment]
Thanks! Yea, I am also not happy with the way I implemented the token part so feel free to play around with that 😄

**Pull request merged**
